
DROP TABLE IF EXISTS users;
CREATE TABLE users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(150),
  email VARCHAR(100),
  password VARCHAR(50)
);

DROP TABLE IF EXISTS stories;
CREATE TABLE stories(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(150),
  subject VARCHAR(150),
  likes INT
)